// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"github.com/jackc/pgtype"
)

type Account struct {
	ID          pgtype.Int4        `json:"id"`
	Uid         pgtype.UUID        `json:"uid"`
	CustomerUid pgtype.UUID        `json:"customer_uid"`
	OpeningDate pgtype.Date        `json:"opening_date"`
	AccountType pgtype.Text        `json:"account_type"`
	Amount      pgtype.Numeric     `json:"amount"`
	Status      pgtype.Int2        `json:"status"`
	UpdatedBy   pgtype.Text        `json:"updated_by"`
	UpdatedDate pgtype.Timestamptz `json:"updated_date"`
}

type Customer struct {
	ID          pgtype.Int4        `json:"id"`
	Uid         pgtype.UUID        `json:"uid"`
	Name        pgtype.Text        `json:"name"`
	DateOfBirth pgtype.Date        `json:"date_of_birth"`
	City        pgtype.Text        `json:"city"`
	Zipcode     pgtype.Text        `json:"zipcode"`
	Status      pgtype.Int2        `json:"status"`
	UpdatedBy   pgtype.Text        `json:"updated_by"`
	UpdatedDate pgtype.Timestamptz `json:"updated_date"`
}

type Transaction struct {
	ID              pgtype.Int4        `json:"id"`
	Uid             pgtype.UUID        `json:"uid"`
	AccountUid      pgtype.UUID        `json:"account_uid"`
	Amount          pgtype.Numeric     `json:"amount"`
	TransactionType pgtype.Text        `json:"transaction_type"`
	CreatedBy       pgtype.Text        `json:"created_by"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
}
